In [21]:
import numpy as np
import pandas as pd
from sklearn import datasets, linear_model
from sklearn.metrics import r2_score

In [22]:
def metrics(m,X,y):
    yhat = m.predict(X)
    print(yhat)
    
    SS_Residual = sum((y-yhat)**2)
    SS_Total = sum((y-np.mean(y))**2)
    r_squared = 1 - (float(SS_Residual))/SS_Total
    adj_r_squared = 1 - (1-r_squared)*(len(y)-1)/(len(y)-X.shape[1]-1)
    
    return r_squared,adj_r_squared

In [23]:
data = pd.DataFrame({"x1": [1,2,3,4,5], "x2": [2.1,4,6.1,8,10.1]})
y = np.array([2.1, 4, 6.2, 8, 9])

In [24]:
data

x1    x2
0   1   2.1
1   2   4.0
2   3   6.1
3   4   8.0
4   5  10.1

In [25]:
y

array([2.1, 4. , 6.2, 8. , 9. ])

In [26]:
model1 = linear_model.LinearRegression()
model1.fit(data.drop("x2", axis = 1),y)
metrics(model1,data.drop("x2", axis=1),y)

[2.3  4.08 5.86 7.64 9.42]


(0.9854441403334163, 0.9805921871112218)

In [27]:
model2 = linear_model.LinearRegression()
model2.fit(data,y)
metrics(model2,data,y)

[2.20666667 4.22       5.76666667 7.78       9.32666667]


(0.9874761549307457, 0.9749523098614914)

In [28]:
r = linear_model.LinearRegression()
r.fit(data,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [29]:
pred = r.predict(data)
r2_score(y, pred)

0.9874761549307457

Ref: https://medium.com/usf-msds/choosing-the-right-metric-for-machine-learning-models-part-1-a99d7d7414e4